# Generated by Django 4.2.9 on 2024-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="comment_count",
            field=models.IntegerField(default=0, verbose_name="文章总数"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="文章内容"),
        ),
        migrations.AlterField(
            model_name="article",
            name="up_count",
            field=models.IntegerField(default=0, verbose_name="文章电点赞数"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="avatar",
            field=models.FileField(default="/avatar/12.jpg", upload_to="avatar/"),
        ),
    ]
